development:
  adapter: postgresql
  encoding: utf8
  database: cash_machine_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: cash_machine_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: cash_machine_production
  pool: 5
  username: 
  password:
